-- 유저 생성 / 권한

-- 계정 생성
CREATE USER PRGMGTEST IDENTIFIED BY 12345;

-- 각종 테이블,인덱스,시퀀스 등등 권한 허용
GRANT CREATE SESSION TO PRGMGTEST;
GRANT CREATE DATABASE LINK TO PRGMGTEST;
GRANT CREATE MATERIALIZED VIEW TO PRGMGTEST;
GRANT CREATE PROCEDURE TO PRGMGTEST;
GRANT CREATE PUBLIC SYNONYM TO PRGMGTEST;
GRANT CREATE ROLE TO PRGMGTEST;
GRANT CREATE SEQUENCE TO PRGMGTEST;
GRANT CREATE SYNONYM TO PRGMGTEST;
GRANT CREATE TABLE TO PRGMGTEST;
GRANT DROP ANY TABLE TO PRGMGTEST;
GRANT CREATE TRIGGER TO PRGMGTEST;
GRANT CREATE TYPE TO PRGMGTEST;
GRANT CREATE VIEW TO PRGMGTEST;

GRANT CREATE ANY INDEX, ALTER ANY INDEX, DROP ANY INDEX TO PRGMGTEST;

----------------------------------------------------------------------------------

-- 공통 코드 테이블




/*----------------------------------------------------------------------------------*/

-- 직원 테이블

CREATE TABLE FL_EMP(
	EMP_NO VARCHAR2(30) PRIMARY KEY,
	EMP_FIRST_REGISTRANT 	VARCHAR2(30) NOT NULL, --최초 등록자
	EMP_FIRST_REGISTER_DATE VARCHAR2(30) NOT NULL, --최조 등록일
	EMP_EDITER_NM 			VARCHAR2(30),          --마지막 수정자
	EMP_EDITED_DATE 		VARCHAR2(30),          --마지막 수정일
	EMP_NM 					VARCHAR2(30) NOT NULL, 
	EMP_EMAIL 				VARCHAR2(50) NOT NULL,
	EMP_PW					VARCHAR2(100) NOT NULL,
	EMP_PHONE_NO 			VARCHAR2(30) NOT NULL,
	EMP_EMER_NO 			VARCHAR2(30) NOT NULL,
	EMP_JOIN_DATE			VARCHAR2(30) NOT NULL,
	EMP_SKILL_LV_C 			VARCHAR2(10) NOT NULL,
	EMP_POS_C 				VARCHAR2(10) NOT NULL
)

/*----------------------------------------------------------------------------------*/
-- 프로젝트 테이블



-- 시퀀스 생성

-- 사번 시퀀스
CREATE SEQUENCE SEQ_FLEMP_NO --시퀀스이름
    INCREMENT BY 1 -- 증감숫자 1
    START WITH 100 -- 시작숫자 1
    MINVALUE 100 -- 최소값 1
    MAXVALUE 10000 -- 최대값 10000
    NOCYCLE; -- 순환하지않음
    


-- 프로시저


-- 로그인 프로시저




-- 프로젝트 업데이트 프로시저



